USE [master]
GO
/****** Object:  Database [BeautySaloon]    Script Date: 22.04.2018 16:51:37 ******/
CREATE DATABASE [BeautySaloon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BeautySaloon', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BeautySaloon.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BeautySaloon_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BeautySaloon_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BeautySaloon] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BeautySaloon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BeautySaloon] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BeautySaloon] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BeautySaloon] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BeautySaloon] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BeautySaloon] SET ARITHABORT OFF 
GO
ALTER DATABASE [BeautySaloon] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BeautySaloon] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BeautySaloon] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BeautySaloon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BeautySaloon] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BeautySaloon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BeautySaloon] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BeautySaloon] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BeautySaloon] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BeautySaloon] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BeautySaloon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BeautySaloon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BeautySaloon] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BeautySaloon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BeautySaloon] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BeautySaloon] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BeautySaloon] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BeautySaloon] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BeautySaloon] SET  MULTI_USER 
GO
ALTER DATABASE [BeautySaloon] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BeautySaloon] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BeautySaloon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BeautySaloon] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BeautySaloon] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BeautySaloon] SET QUERY_STORE = OFF
GO
USE [BeautySaloon]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
ALTER DATABASE [BeautySaloon] SET  READ_WRITE 
GO

CREATE TABLE employees
(  
   employeeID int IDENTITY (1,1) NOT NULL,
   surname varchar(30) NOT NULL,
   name varchar(30) NOT NULL,
   lastname varchar(30) NOT NULL,
   phone_number varchar(20) NOT NULL,
   address varchar(50) NOT NULL,
   specialization varchar(30) NOT NULL,
   start_date date NOT NULL,
   CONSTRAINT PK_employees_employeeID PRIMARY KEY CLUSTERED (employeeID)
);

CREATE TABLE services
(  
   serviceID int IDENTITY (1,1) NOT NULL,
   name varchar(30) NOT NULL,
   price int NOT NULL,
   comment text,
   CONSTRAINT PK_services_serviceID PRIMARY KEY CLUSTERED (serviceID)
);

CREATE TABLE clients
(  
   clientID int IDENTITY (1,1) NOT NULL,
   surname varchar(30),
   name varchar(30) NOT NULL,
   phone_number varchar(20) NOT NULL,
   CONSTRAINT PK_clients_clientID PRIMARY KEY CLUSTERED (clientID)
);

CREATE TABLE records
(  
   recordID int IDENTITY (1,1) NOT NULL,
   client_id int FOREIGN KEY REFERENCES clients(clientID),
   employee_id int FOREIGN KEY REFERENCES employees(employeeID),
   service_id int FOREIGN KEY REFERENCES services(serviceID),
   date date NOT NULL,
   time time NOT NULL,
   comment text,
   CONSTRAINT PK_records_recordID PRIMARY KEY CLUSTERED (recordID)
);

CREATE TABLE shares
(  
   shareID int IDENTITY (1,1) NOT NULL,
   name varchar(30) NOT NULL,
   start_date date NOT NULL,
   expiration_date date,
   CONSTRAINT PK_shares_shareID PRIMARY KEY CLUSTERED (shareID)
);

CREATE TABLE discounts
(  
   discountID int IDENTITY (1,1) NOT NULL,
   share_id int FOREIGN KEY REFERENCES shares(shareID),
   service_id int FOREIGN KEY REFERENCES services(serviceID),
   value int NOT NULL,
   CONSTRAINT PK_discounts_discountID PRIMARY KEY CLUSTERED (discountID)
);